Repository UCR-CS110-S23/project-methinks, pull requests merged in 2023-05, with the labels that each got.

#1 Setup Repo
  .eslintignore
  .eslintrc.js
  .github/workflows/pull_requests.yaml
  .gitignore
  .husky/pre-commit
  .prettierignore
  components/Hello.jsx
  components/Test.jsx
  jsconfig.json
  next.config.js
  package-lock.json
  package.json
  pages/_app.js
  pages/_document.js
  pages/api/hello.js
  pages/index.js
  postcss.config.js
  public/favicon.ico
  public/next.svg
  public/thirteen.svg
  public/vercel.svg
  styles/Home.module.css
  styles/globals.css
  tailwind.config.js
Labels: READY FOR REVIEW, Repository

#16 Turn Off React Strict Mode
  components/Feed/Comments.jsx
  next.config.js
  pages/index.js
Labels: READY FOR REVIEW

#17 public sans added
  pages/_app.js
  tailwind.config.js
Labels: READY FOR REVIEW, Frontend

#21 color pallette
  pages/index.js
  tailwind.config.js
Labels: READY FOR REVIEW, Frontend

#22 Refacted Post Page for Animations
  components/Feed/Comment.jsx
  components/Feed/Comments.jsx
  components/Layout.jsx
  components/Post/Cards.jsx
  components/Post/FleetingThought.jsx
  components/Post/Prompt.jsx
  components/Post/Tags.jsx
  components/Post/ThinkOutLoud.jsx
  components/Post/Thought.jsx
  components/Tag.jsx
  package-lock.json
  package.json
  pages/_app.js
  pages/post.js
  tailwind.config.js
Labels: READY FOR REVIEW, Frontend

#38 feed
  components/Feed/FeedPost.jsx
  components/Feed/FeedPosts.jsx
  package-lock.json
  package.json
  pages/comment.js
  pages/feed.js
  public/henry2.jpg
  public/hovercloud.svg
  public/mintcloud.svg
Labels: READY FOR REVIEW, Frontend

#28 created profile
  components/Feed/Post.jsx
  components/Feed/Posts.jsx
  components/Feed/SortButton.jsx
  components/Layout.jsx
  components/Post/FleetingThought.jsx
  components/Post/Prompt.jsx
  components/Post/ThinkOutLoud.jsx
  components/Post/Thought.jsx
  components/Profile/Calendar.jsx
  components/Profile/FriendsProfile.jsx
  components/Profile/UserProfile.jsx
  package-lock.json
  package.json
  pages/_app.js
  pages/feed.js
  pages/feed/[id].js
  pages/index.js
  pages/landing.js
  pages/post.js
  pages/profile/[id].js
  public/assets/landing_cloud.svg
  styles/Home.module.css
  styles/globals.css
  tailwind.config.js
Labels: READY FOR REVIEW, Frontend

#41 Mgolwalla/topicpills
  components/Feed/Dropdown.jsx
  components/Feed/FeedPosts.jsx
  components/Feed/TopicBar.jsx
  pages/feed.js
Labels: READY FOR REVIEW, Frontend
