Repository UCR-CS110-S23/project-methinks, pull requests merged in 2023-06, with the labels that each got.

#51 Build The House 🛠️
  .github/workflows/pull_requests.yaml
  .gitignore
  components/Feed/Comment.jsx
  components/Feed/Comments.jsx
  components/Feed/FeedPosts.jsx
  components/Feed/Post.jsx
  components/Feed/Posts.jsx
  components/Feed/SortButton.jsx
  components/Feed/Tag.jsx
  components/Feed/Tags.jsx
  components/Layout.jsx
  components/Layout/ProtectedPage.jsx
  components/Layout/PublicPage.jsx
  components/Navigation.jsx
  components/Post/Tags.jsx
  components/Profile/Calendar.jsx
  components/Profile/FriendsProfile.jsx
  components/Profile/UserProfile.jsx
  components/Tag.jsx
  jsconfig.json
  lib/mongodb.js
  lib/password.js
  lib/username.js
  lib/users.js
  next.config.js
  package-lock.json
  package.json
  pages/_app.js
  pages/api/auth/[...nextauth].js
  pages/api/auth/setupUsername.js
  pages/api/auth/signup.js
  pages/api/hello.js
  pages/feed.js
  pages/feed/[id].js
  pages/landing.js
  pages/newUser.js
  pages/post.js
  pages/profile/[id].js
  pages/signin.js
  pages/signup.js
  public/data/tags.js
  styles/globals.css
  tailwind.config.js
Labels: READY FOR REVIEW, Frontend, Backend

#73 Char count and solved duplicate text across post cards
  components/Post/FleetingThought.jsx
  components/Post/Prompt.jsx
  components/Post/Thought.jsx
Labels: Frontend

#42 Kliang/nav bar
  .husky/.gitignore
  package-lock.json
Labels: DO NOT MERGE, Frontend

#80 Mgolwalla/mwah
  components/Feed/Comment.jsx
  components/Feed/Comments.jsx
  components/Feed/Post.jsx
  components/Feed/Posts.jsx
  components/Feed/SortButton.jsx
  components/Feed/Tags.jsx
  components/Navigation.jsx
  components/Profile/FriendsProfile.jsx
  lib/messageHandler.js
  lib/posts.js
  package-lock.json
  package.json
  pages/api/getLikes.js
  pages/api/socket.js
  pages/chat2.js
  pages/feed.js
  pages/feed/[id].js
  pages/profile/[id].js
Labels: READY FOR REVIEW

#81 nav links
  components/Feed/SortButton.jsx
  components/Navigation.jsx
  components/Profile/FriendsProfile.jsx
  pages/api/addMessage.js
  pages/api/getMessages.js
  pages/chat.js
  public/data/tags.js
Labels: DO NOT MERGE, READY FOR REVIEW
